
List categoryList = [
  {
    'name': 'شقق',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'محلات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مطاعم ومقاهي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'فلل و منازل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'أراضي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مشاركة سكن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'عمارات ومباني',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'شقق مفروشة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'شاليهات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'عقارات دولية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مصانع',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مكاتب',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مجمعات تجارية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مستودعات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'سكن عمال',
    'image': "",
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'بيت شعبي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'فنادق و منتجعات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'استديو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'قيد الإنشاء',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مزارع',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'قاعات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'متفرقات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مخيمات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'فلل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'منازل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'متفرقات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'تويوتا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'هيونداي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'فورد',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'شفروليه',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'كيا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ميتسوبيشي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'مرسيدس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'نيسان',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سوزوكي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'هوندا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ايسوزي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'جي ام سي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'رينو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': 'رينو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': 'رينو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ام جي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'فولفو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'استيراد سيارات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'اودي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بونتياك',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بي ام دبليو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'دايهاتسو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'دودج',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سكودا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'شيري',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لكزس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ميركيري',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'همر ',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'مازدا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'استون مارتن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'اسيا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'الفاروميو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'انفينيتي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'اوبل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'اوستن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'اولدس موبيل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بروتن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بليموث',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بنتلي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بورش',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بوغاتي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بويك',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'بيجو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'تاتا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'جاك',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'جاكور',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'جيب',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'داتسون',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'داسيا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'دايوو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'دفسك',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'روفر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'رولز رويس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سابا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سامسونغ',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ستروين',
    'image': 'سمارت',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سوبارو',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سيات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سيمكا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'فراري',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'فولكس واجن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'فيات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'كاديلاك',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'كرايسلر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'كلاسيكية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لادا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لامبرغيني',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لاند روفر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لانسيا',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لوتس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'لينكولن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'مازيراتي',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ماكلارين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'مورغان',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'ميني كوبر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'سياحة ومطاعم',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'سائق',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'حسابات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'عمال',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مبيعات وتسويق',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مهندس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'ادارة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'طب وتمريض',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'حرفيين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تقني',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'موظفين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مقاولات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'متفرقات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'خدمة الزبائن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'عمال ديليفري',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تصميم',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'عمالة منزلية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مدخل بيانات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تزيين وتجميل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'حراسة وأمن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'عمال تنظيف',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تعليم وتدريس',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'كمبيوتر وشبكات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تكييف وتبريد',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'سكرتارية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'حدائق و مناظر طبيعية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'موارد بشرية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'شراكة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'خياطين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'برمجة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'محاماة و قانون',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'لياقة بدنية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'سياحة وسفر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'علاقات عامة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'حضانة أطفال',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مونتاج وإخراج',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'تصميم مواقع',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'مترجمين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'محررين',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'أزياء',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'فنون جميلة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'دروس خصوصية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'تاكسي وتوصيل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'مقاولات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'استقدام عمالة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'المباني والمنازل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'اعمال واستثمار',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات الصيانة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'نقل عفش',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات تنظيف',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات عامة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'دعاية وإعلان',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'قرض',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'ضريبة ومال',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'تخليص معاملات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'مكافحة الحشرات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'مهارات وتدريب',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات زراعية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'اتصالات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'انترنت',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'تأجير سيارات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'طبخ منزلية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات السيارات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'شحن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات عقارية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'خدمات احترافية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'صحة وجمال',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'موارد بشرية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'محاماة وقانون',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'تنظيم حفلات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'ممتلكات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'حواسيب',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'حراسة وأمن',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'سياحة وسفر',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'ترجمة',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'تسلية',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': 'مفقودات',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'خدمات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
  {
    'name': '',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'متفرقات',
  },
];


List optionList= [
  {
    'name': 'للبيع',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'للإيجار',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مطلوب للإيجار',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },
  {
    'name': 'مطلوب للشراء',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'عقارات',
  },



  {
    'name': 'للبيع',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },
  {
    'name': 'مطلوب للشراء',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'سيارات',
  },


  {
    'name': 'فرص عمل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
  {
    'name': 'يطلب عمل',
    'image': '',
    'title': '',
    'count': '',
    'parent': 'وظائف',
  },
];
